services:
  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lab7
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


